// Stitch 프로젝트 "포켓몬 굿즈샵 디자인"의 tailwind.config 토큰을 그대로 옮긴 것
const fontStack = ['"Plus Jakarta Sans"', '"Noto Sans KR"', 'sans-serif'];

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#ffb3b0',
        'on-secondary-fixed': '#251a00',
        'on-error-container': '#93000a',
        background: '#fff8f6',
        primary: '#b52330',
        'tertiary-container': '#55a18d',
        'on-background': '#211a17',
        'on-tertiary-fixed': '#002019',
        'secondary-container': '#fdc73a',
        'primary-container': '#ff5a5f',
        error: '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#ffb3b0',
        'on-surface': '#211a17',
        'secondary-fixed': '#ffdf9a',
        tertiary: '#146a59',
        outline: '#8e706f',
        'error-container': '#ffdad6',
        secondary: '#775a00',
        'inverse-on-surface': '#fceee8',
        'on-error': '#ffffff',
        'on-tertiary-container': '#003329',
        'on-primary': '#ffffff',
        surface: '#fff8f6',
        'secondary-fixed-dim': '#f4bf32',
        'tertiary-fixed-dim': '#88d5bf',
        'on-secondary': '#ffffff',
        'outline-variant': '#e2bebc',
        'on-surface-variant': '#5a403f',
        'inverse-surface': '#372f2b',
        'primary-fixed': '#ffdad8',
        'on-tertiary-fixed-variant': '#005142',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#eee0da',
        'surface-container-low': '#fff1eb',
        'surface-variant': '#eee0da',
        'surface-container': '#f9ebe5',
        'surface-dim': '#e5d7d2',
        'on-primary-fixed': '#410007',
        'surface-container-high': '#f3e5e0',
        'surface-tint': '#b52330',
        'surface-bright': '#fff8f6',
        'on-secondary-container': '#6f5400',
        'on-primary-container': '#61000e',
        'on-primary-fixed-variant': '#92001b',
        'on-secondary-fixed-variant': '#5a4300',
        'tertiary-fixed': '#a4f2db',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        gutter: '1.25rem',
        margin: '2rem',
      },
      fontFamily: {
        'body-sm': fontStack,
        'body-md': fontStack,
        'body-lg': fontStack,
        'label-sm': fontStack,
        'label-md': fontStack,
        'label-lg': fontStack,
        'headline-sm': fontStack,
        'headline-md': fontStack,
        'headline-lg': fontStack,
        'headline-lg-mobile': fontStack,
        'display-lg': fontStack,
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '700' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-lg': ['15px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['40px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};
